"""
Core data models for rmrf.

Uses pydantic for validation and serialization.
"""

from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator


class Verdict(str, Enum):
    """OPA policy verdict types."""

    ALLOW = "allow"
    DENY = "deny"
    REQUIRE_APPROVAL = "require_approval"


class RiskLevel(str, Enum):
    """Risk assessment levels."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class EventPhase(str, Enum):
    """Lifecycle event phases."""

    PLAN_CREATED = "plan_created"
    PLAN_VALIDATED = "plan_validated"
    BACKUP_CREATED = "backup_created"
    BACKUP_COMPLETED = "backup_completed"
    DELETION_STARTED = "deletion_started"
    DELETION_COMPLETED = "deletion_completed"
    DELETION_FAILED = "deletion_failed"
    APPLIED = "applied"
    CANCELED = "canceled"
    ROLLBACK_COMPLETED = "rollback_completed"
    ROLLBACK_EXECUTED = "rollback_executed"
    CLOSEOUT_COMPLETED = "closeout_completed"
    AUTO_HALT = "auto_halt"
    # Locking events
    LOCK_ACQUIRED = "lock_acquired"
    LOCK_RELEASED = "lock_released"
    LOCK_FAILED = "lock_failed"
    # Approval events
    APPROVAL_REQUIRED = "approval_required"
    APPROVAL_GRANTED = "approval_granted"


class Environment(BaseModel):
    """
    Environment metadata with optional signature verification.

    Read from /etc/rmrf.env, /etc/system.env, or $RM_ENVIRONMENT.
    """

    env: str = Field(..., description="Environment name (dev, staging, prod, etc.)")
    signature: str | None = Field(None, description="SHA256 signature for verification")

    @field_validator("env")
    @classmethod
    def validate_env(cls, v: str) -> str:
        """Ensure environment name is lowercase and non-empty."""
        if not v or not v.strip():
            raise ValueError("Environment name cannot be empty")
        return v.lower().strip()


class ProtectionLevel(BaseModel):
    """
    Protection level configuration defining safety constraints.

    Can be loaded from default or custom YAML files.
    """

    name: str = Field(..., description="Protection level name")
    description: str = Field(..., description="Human-readable description")
    default_environment: str | None = Field(
        None, description="Default environment this level applies to"
    )
    max_files: int | None = Field(None, description="Maximum files allowed in plan", ge=0)
    max_bytes: int | None = Field(None, description="Maximum total bytes allowed", ge=0)
    require_backup: bool = Field(True, description="Whether backup is required before deletion")
    require_audit: bool = Field(True, description="Whether audit events must be emitted")
    require_confirmation: bool = Field(False, description="Whether human confirmation is required")
    require_approval: bool = Field(False, description="Whether multi-user approval is required")
    retention_days: int = Field(7, description="How long to retain backups", ge=0)
    allow_simulation_only: bool = Field(False, description="If true, only dry-run mode is allowed")

    @field_validator("name")
    @classmethod
    def validate_name(cls, v: str) -> str:
        """Ensure name is lowercase with hyphens."""
        if not v or not v.strip():
            raise ValueError("Protection level name cannot be empty")
        return v.lower().strip()


class RiskScore(BaseModel):
    """Risk assessment for a deletion plan."""

    level: RiskLevel = Field(..., description="Overall risk level")
    score: int = Field(..., description="Numeric risk score (0-100)", ge=0, le=100)
    reasons: list[str] = Field(default_factory=list, description="Reasons for risk assessment")


class PolicyVerdict(BaseModel):
    """Result from OPA policy evaluation."""

    verdict: Verdict = Field(..., description="Policy decision")
    policy_id: str | None = Field(None, description="Policy that made decision")
    reason_code: str | None = Field(None, description="Machine-readable reason")
    message: str | None = Field(None, description="Human-readable message")
    reasons: list[str] = Field(default_factory=list, description="List of reasons for the decision")
    risk: RiskScore | None = Field(None, description="Risk assessment")


class UserContext(BaseModel):
    """User context for policy evaluation."""

    id: str = Field(..., description="User ID")
    role: str | None = Field(None, description="User role")
    groups: list[str] = Field(default_factory=list, description="User groups")


class Plan(BaseModel):
    """
    Deletion plan containing targets and metadata.

    Generated by the planning engine and validated before execution.
    """

    plan_id: str = Field(..., description="Unique plan identifier")
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), description="Plan creation timestamp"
    )
    environment: str = Field(..., description="Environment where plan will execute")
    protection_level: str = Field(..., description="Protection level name")
    targets: list[str] = Field(..., description="Target paths to delete", min_length=1)
    file_count: int = Field(..., description="Total number of files", ge=0)
    total_bytes: int = Field(..., description="Total size in bytes", ge=0)
    risk_score: RiskScore | None = Field(None, description="Risk assessment")
    user: UserContext | None = Field(None, description="User context")
    scenario: str | None = Field(None, description="Scenario description")
    validated: bool = Field(False, description="Whether plan has been validated")
    validated_at: datetime | None = Field(None, description="Validation timestamp")
    policy_verdict: PolicyVerdict | None = Field(None, description="OPA policy verdict")
    backup_path: str | None = Field(None, description="Path to backup directory")
    audit_id: str | None = Field(None, description="Associated audit ID")
    expires_at: datetime | None = Field(None, description="Plan expiration time")
    dry_run: bool = Field(False, description="Whether this is a dry-run")
    executed_at: datetime | None = Field(None, description="Execution timestamp")
    verification_count: int = Field(0, description="Number of times verification was run")
    last_verified_at: datetime | None = Field(None, description="Last verification timestamp")
    verification_passed: bool = Field(False, description="Whether verification passed")
    rollback_at: datetime | None = Field(None, description="Rollback timestamp")
    rollback_comment: str | None = Field(None, description="Operator comment explaining rollback")
    closeout_at: datetime | None = Field(None, description="Closeout timestamp")
    closeout_comment: str | None = Field(None, description="Operator comment on closeout")
    learn_comment: str | None = Field(None, description="Lessons learned / post-completion notes")
    near_miss: bool = Field(False, description="Whether this plan was abandoned (near miss)")
    near_miss_at: datetime | None = Field(None, description="Near miss timestamp")
    near_miss_comment: str | None = Field(
        None, description="Operator comment explaining why plan was abandoned"
    )
    failed: bool = Field(False, description="Whether this plan has failed")
    failed_at: datetime | None = Field(None, description="Failure timestamp")
    failed_comment: str | None = Field(None, description="Operator comment explaining failure")
    # Locking fields
    lock_id: str | None = Field(None, description="Associated directory lock ID")
    # Approval fields
    requires_approval: bool = Field(False, description="Whether plan requires approval")
    approved: bool | None = Field(
        None, description="Whether plan has been approved (None/False/True)"
    )
    approval_id: str | None = Field(None, description="Unique approval ID")
    approved_by_uid: int | None = Field(None, description="User ID who approved")
    approved_at: datetime | None = Field(None, description="Approval timestamp")
    approval_comment: str | None = Field(None, description="Approval comment")
    created_by_uid: int | None = Field(None, description="User ID who created plan")

    @field_validator("targets")
    @classmethod
    def validate_targets(cls, v: list[str]) -> list[str]:
        """Ensure all targets are non-empty strings."""
        if not v:
            raise ValueError("At least one target must be specified")
        for target in v:
            if not target or not target.strip():
                raise ValueError("Target path cannot be empty")
        return v

    @field_validator(
        "created_at",
        "validated_at",
        "expires_at",
        "executed_at",
        "last_verified_at",
        "rollback_at",
        "closeout_at",
        "near_miss_at",
        "failed_at",
        "approved_at",
    )
    @classmethod
    def ensure_timezone_aware(cls, v: datetime | None) -> datetime | None:
        """Ensure datetime fields are timezone-aware."""
        if v is None:
            return v
        if v.tzinfo is None:
            # Assume UTC if no timezone info
            return v.replace(tzinfo=timezone.utc)
        return v

    def is_expired(self) -> bool:
        """Check if plan has expired."""
        if self.expires_at is None:
            return False
        return datetime.now(timezone.utc) > self.expires_at

    def check_targets_exist(self) -> list[tuple[Path, str]]:
        """Check if all plan targets exist. Returns list of (path, error) tuples."""
        errors: list[tuple[Path, str]] = []
        for target_str in self.targets:
            target = Path(target_str)
            if not target.exists():
                errors.append((target, "Target does not exist"))
        return errors

    def get_workflow_stage(self) -> str:
        """
        Get current workflow stage.

        Returns:
            Stage name: 'planned', 'validated', 'staged', 'applied', 'verified', 'closed',
            'rollback', 'near-miss', 'denied', 'approval-required', or 'failed'
        """
        # Terminal states
        if self.failed:
            return "failed"
        if self.near_miss:
            return "near-miss"
        if self.rollback_at:
            return "rollback"
        if self.closeout_at:
            return "closed"

        # Check if denied or requires approval
        if self.policy_verdict:
            if self.policy_verdict.verdict == Verdict.DENY:
                return "denied"
            elif self.policy_verdict.verdict == Verdict.REQUIRE_APPROVAL:
                return "approval-required"

        # Normal workflow progression
        if self.verification_passed:
            return "verified"
        if self.executed_at:
            return "applied"
        if self.backup_path:
            return "staged"
        if self.validated:
            return "validated"
        return "planned"

    def can_validate(self) -> tuple[bool, str | None]:
        """
        Check if plan can be validated.

        Returns:
            Tuple of (can_proceed, error_message)
        """
        current_stage = self.get_workflow_stage()
        if self.validated:
            next_action = self._get_next_action(current_stage)
            return False, f"Plan is already at stage '{current_stage}'. {next_action}"
        if self.is_expired():
            return False, "Plan has expired"
        return True, None

    def can_stage(self) -> tuple[bool, str | None]:
        """
        Check if plan can be staged (backed up).

        Returns:
            Tuple of (can_proceed, error_message)
        """
        current_stage = self.get_workflow_stage()
        if self.backup_path:
            next_action = self._get_next_action(current_stage)
            return False, f"Plan is already at stage '{current_stage}'. {next_action}"
        if not self.validated:
            return False, f"Plan is at stage '{current_stage}'. Next: run 'rmrf validate' first"
        if self.is_expired():
            return False, "Plan has expired"
        return True, None

    def can_apply(self) -> tuple[bool, str | None]:
        """
        Check if plan can be applied (executed).

        Returns:
            Tuple of (can_proceed, error_message)
        """
        current_stage = self.get_workflow_stage()
        if self.executed_at:
            next_action = self._get_next_action(current_stage)
            return False, f"Plan is already at stage '{current_stage}'. {next_action}"
        # Check validation before backup - workflow order is validate -> stage -> apply
        if not self.validated:
            return False, f"Plan is at stage '{current_stage}'. Next: run 'rmrf validate' first"
        if not self.backup_path:
            return False, f"Plan is at stage '{current_stage}'. Next: run 'rmrf stage' first"
        if self.is_expired():
            return False, "Plan has expired"
        return True, None

    def can_closeout(self) -> tuple[bool, str | None]:
        """
        Check if plan can be closed out.

        Returns:
            Tuple of (can_proceed, error_message)
        """
        current_stage = self.get_workflow_stage()
        if self.closeout_at:
            return False, "Plan is already closed out"
        if not self.executed_at:
            return False, f"Plan is at stage '{current_stage}'. Next: run 'rmrf apply' first"
        return True, None

    def _get_next_action(self, current_stage: str) -> str:
        """Get next action suggestion based on current stage."""
        if current_stage == "planned":
            return "Next: run 'rmrf validate'"
        elif current_stage == "validated":
            return "Next: run 'rmrf stage'"
        elif current_stage == "staged":
            return "Next: run 'rmrf apply'"
        elif current_stage == "applied":
            return "Next: run 'rmrf verify' or 'rmrf closeout'"
        elif current_stage == "verified":
            return "Next: run 'rmrf closeout' or 'rmrf learn'"
        elif current_stage == "closed":
            return "Workflow complete. Run 'rmrf learn' to add notes (optional)"
        elif current_stage == "rollback":
            return "Plan was rolled back"
        elif current_stage == "near-miss":
            return "Plan was abandoned"
        return ""


class RollbackManifest(BaseModel):
    """
    Rollback manifest for restoring deleted files.

    Contains checksums and metadata for backup verification.
    """

    manifest_id: str = Field(..., description="Unique manifest identifier")
    plan_id: str = Field(..., description="Associated plan ID")
    environment: str = Field(..., description="Environment")
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Manifest creation timestamp",
    )
    files: int = Field(..., description="Number of backed up files", ge=0)
    total_bytes: int = Field(..., description="Total backup size", ge=0)
    checksums: dict[str, str] = Field(
        default_factory=dict,
        description="File path to SHA256 checksum mapping",
    )
    symlinks: dict[str, str] = Field(
        default_factory=dict,
        description="Symlink path to target mapping (path -> link target)",
    )
    targets: list[str] = Field(
        default_factory=list,
        description="Original target paths (for calculating relative backup paths)",
    )
    backup_root: str = Field(..., description="Root backup directory")
    retention_days: int = Field(..., description="Retention period", ge=0)

    @field_validator("checksums")
    @classmethod
    def validate_checksums(cls, v: dict[str, str]) -> dict[str, str]:
        """Ensure all checksums are valid SHA256 format."""
        for path, checksum in v.items():
            if not checksum.startswith("sha256:"):
                raise ValueError(f"Checksum for {path} must be in format 'sha256:...'")
        return v

    @field_validator("created_at")
    @classmethod
    def ensure_timezone_aware(cls, v: datetime) -> datetime:
        """Ensure datetime fields are timezone-aware."""
        if v.tzinfo is None:
            # Assume UTC if no timezone info
            return v.replace(tzinfo=timezone.utc)
        return v


class AuditEvent(BaseModel):
    """
    Structured audit event for lifecycle tracking.

    Emitted at each stage of the deletion workflow.
    """

    event_id: str = Field(..., description="Unique event identifier")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), description="Event timestamp"
    )
    phase: EventPhase = Field(..., description="Lifecycle phase")
    environment: str | None = Field(None, description="Environment")
    protection_level: str | None = Field(None, description="Protection level")
    plan_id: str | None = Field(None, description="Associated plan ID")
    audit_id: str | None = Field(None, description="Audit session ID")
    user_id: str | None = Field(None, description="User ID")
    result: str | None = Field(None, description="Event result (success, failure, etc.)")
    message: str | None = Field(None, description="Human-readable message")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Additional event metadata")

    @field_validator("timestamp")
    @classmethod
    def ensure_timezone_aware(cls, v: datetime) -> datetime:
        """Ensure datetime fields are timezone-aware."""
        if v.tzinfo is None:
            # Assume UTC if no timezone info
            return v.replace(tzinfo=timezone.utc)
        return v

    model_config = ConfigDict(use_enum_values=True)

    @classmethod
    def for_closeout(
        cls,
        plan: "Plan",
        backup_removed: bool,
        keep_backup: bool,
    ) -> "AuditEvent":
        """Create audit event for plan closeout."""
        import uuid

        return cls(
            event_id=f"evt-{uuid.uuid4().hex[:16]}",
            phase=EventPhase.CLOSEOUT_COMPLETED,
            environment=plan.environment,
            protection_level=plan.protection_level,
            plan_id=plan.plan_id,
            user_id=plan.user.id if plan.user else None,
            result="success",
            message=f"Plan {plan.plan_id} closed out. Backup "
            + ("removed" if backup_removed else "retained"),
            metadata={
                "backup_removed": backup_removed,
                "keep_backup": keep_backup,
                "file_count": plan.file_count,
                "total_bytes": plan.total_bytes,
            },
        )


class DirectoryLock(BaseModel):
    """
    Directory lock to prevent concurrent operations.

    Simple TTL-based locking with exact path matching.
    """

    lock_id: str = Field(..., description="Unique lock identifier")
    directory_path: str = Field(..., description="Canonical absolute path")
    plan_id: str = Field(..., description="Associated plan ID")
    locked_by_uid: int = Field(..., description="User ID who created lock")
    locked_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Lock creation timestamp",
    )

    @field_validator("locked_at")
    @classmethod
    def ensure_timezone_aware(cls, v: datetime) -> datetime:
        """Ensure datetime field is timezone-aware."""
        if v.tzinfo is None:
            return v.replace(tzinfo=timezone.utc)
        return v
